---
- name: Configuring Apache HTTPD
  hosts: web
  become: True
  gather_facts: True
  tasks:

    - name: Ensuring httpd package presence
      yum:
        name: httpd
        state: present    #latest
      when: (ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Fedora")

    - name: Copying index.html
      copy:
        src: ./files/index.html          #./files/
        dest: /var/www/html/index.html   #/var/www/html/
        mode: preserve
        
    - name: Configuring firewalld to allow http service
      firewalld:
        service: http
        state: enabled
        immediate: true
        permanent: true
      notify: firewall changed

    - name: Starting httpd services
      service:
        name: httpd
        state: started
        enabled: true
  
  handlers:
    - name: firewall changed
      service:
        name: firewalld
        state: restarted
        enabled: true 


- name: Testing connectivity
  hosts: localhost
  tasks:

    - name: Connecting to webserver
      uri:
        url: http://{{ item }}/index.html
        return_content: yes
        status_code: 200
      loop: "{{ groups.all }}"

