---
- name: Public key is being deployed to managed hosts for Ansible
  hosts: web
  tasks:

    - name: Ensure key is in root's ~/.ssh/authorized_hosts
      authorized_key:
        user: root
        state: present
        key: '{{ item }}'
      with_file:
        - ~/.ssh/id_rsa.pub
...
